### ISSUE TITLE
Bull Fails Silently

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [nestjs/bull#1010] opened 2021-11-16 21:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I came accross this issue when attempting to connect to a cluster. Here is my NestJS code
```typescript
export const REDIS_PROVIDER_FUNCTION = (type: string) => {
  if (configService.getRedisCluster()) {
    logger.verbose(`Initializing Redis Cluster Connection for ${type}`);
    return new Redis.Cluster(
      [redisConfig],
      configService.getRedisClusterOptions()
    );
  } else {
    logger.verbose(`Initializing Redis Instance Connection for ${type}`);
    return new Redis(redisConfig);
  }
};
const bullModule = BullModule.forRoot({
  createClient: (type, options) => REDIS_PROVIDER_FUNCTION(`bull - ${type}`),
  prefix: 'queue_',
  defaultJobOptions: {
    attempts: 1,
    removeOnComplete: true,
    removeOnFail: true
  }
});
```

This fails due to errors in bull described here https://github.com/OptimalBits/bull/blob/develop/PATTERNS.md#redis-cluster. However, bull actually broadcasts the error. See the following code for example:

```typescript
  async createDirectBullQueue(queueType: QueueType) {
    this.logger.log(`Creating Bull Queue ${queueType}`);
    const newQueue = BullQueue(queueType, {
      prefix: 'native_queue_',
      createClient: () => REDIS_PROVIDER_FUNCTION('Native Bull')
    });
    const proccessor = newQueue.process((job) => {
      this.logger.log(`Bull Queue ${queueType} processing`);
      return new Promise((resolve, _) => setTimeout(resolve, 3 * 1000));
    });
    this.logger.log(`Adding Empty Job to Bull ${queueType}`);
    await newQueue.add({});
    await new Promise((resolve, reject) => {
      newQueue.on('completed', () => {
        this.logger.log(`Bull Queue ${queueType} successfully completed job`);
        resolve(null);
      });
    });
    await newQueue.obliterate();
  }
```
This second bit of code will throw an error. However, the default NestJS config won't. The only indication a user will have that this isn't working is lack of data in redis. 

I would expect an error on Queue creation to be caught and logged by NestJS.

### Minimum reproduction code

In MR

### Steps to reproduce

1. Create a Bull module with bad config, mine was a bad cluster connection.
2. Try to process a job. 

### Expected behavior

I would expect errors like this to be logged. 

### Package version

8.1.3

### Bull version

3.29.2

### NestJS version

8.1.3

### Node.js version

14.17.6

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment] 2021-11-17 08:28
Would you like to create a PR for this issue?

**Comment by JustAnotherSoftwareDeveloper** [comment] 2021-11-17 21:02
So on quick glance I think a "correct" solution might run deeper. The provider factory function should already be throwing an error. Is there any built in mechanism to catch failures in a provider factor function?

**Comment by kamilmysliwiec** [comment] 2021-11-18 08:07
> Is there any built in mechanism to catch failures in a provider factor function?

Errors thrown in factories should be bubbled up and should prevent the app from bootstrapping.

**Comment by JustAnotherSoftwareDeveloper** [comment] 2021-11-18 17:33
So I did some more digging. Bull is not failing on queue instantiation. It's failing on `add`. Do you have any idea why that error isn't bubbling up? It's 100% failing when I create a bull queue directly, but not failing in the injected queue.

**Comment by kamilmysliwiec** [comment] 2021-11-19 07:24
> It's 100% failing when I create a bull queue directly, but not failing in the injected queue.

This doesn't seem to be possible.

**Comment by zfanta** [comment] 2021-11-22 09:25
Have you tried using prefix with brackets? `prefix: 'queue_'` -> `prefix: '{queue_}'`, `prefix: 'native_queue_'` -> `prefix: '{native_queue_}'`

I had similar issue and using prefix with brackets in `forRoot` function.

**Comment by JustAnotherSoftwareDeveloper** [comment] 2021-11-23 13:21
@zfanta That is exactly how I fixed it. The issue isn't that I am unable to fix it. The issue is that the methods should be throwing errors when they're not.

@kamilmysliwiec In fairness, I have only reproduced the issue in my company's application. Would you mind leaving this issue open? I want to create a minimal project with a redis cluster running in docker-compose to see if I can reproduce it that way. I just don't really have the time now.

**Comment by kamilmysliwiec** [comment] 2021-11-24 07:44
This package is just a very tiny wrapper around the original `bull` package and based on the conversation above, I'm convinced this isn't related to this lib but rather to `bull` itself. I'll close this issue as we can't reproduce it but feel free to create a new one once you have a reproducible example.

**Closed by kamilmysliwiec** 2021-11-24 07:44 UTC
Labels: bug, needs triage
